name: Build Ionic Vue for Android

on:
    release:
      types: [published]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20'

            - name: Install dependencies
              run: npm install

            - name: Build Ionic Vue app
              run: npm run build

            - name: Install Capacitor CLI
              run: npm install -g @capacitor/cli

            - name: Remove existing Android platform
              run: |
                if [ -d "android" ]; then
                  rm -rf android
                fi

            - name: Add Android platform
              run : npx cap add android

            - name: Sync Capacitor
              run: npx cap sync

            - name: Install Java 17
              run: sudo apt-get install openjdk-17-jdk

            - name: Set JAVA_HOME
              run: echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV

            - name: Fix Gradle Permissions
              run: chmod +x android/gradlew

            - name: Decode Keystore
              run: |
                echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > my-release-key.keystore

            - name: Configure Signing in Gradle
              run: |
                mkdir -p android/app/src/main/res
                echo "android.signingConfigs.release {
                  storeFile file('my-release-key.keystore')
                  storePassword '${{ secrets.KEYSTORE_PASSWORD }}'
                  keyAlias '${{ secrets.KEY_ALIAS }}'
                  keyPassword '${{ secrets.KEY_PASSWORD }}'
                }

                android.buildTypes.release {
                  signingConfig signingConfigs.release
                }" > android/app/build.gradle
                
            - name: Build Android
              run: |
                cd android
                ./gradlew assembleRelease

            - name: List APK Files
              run: |
                  cd android/app/build/outputs/apk/release
                  ls -l

            - name: Upload APK
              uses: actions/upload-artifact@v3
              with:
                name: android-apk
                path: android/app/build/outputs/apk/release/app-release-unsigned.apk
